### ISSUE TITLE
Server environment & database

### ISSUE THREAD

**Issue by jslemmer** [LSone1/2020-GPW-L5K2-A#13]
I have created a new server environment and database for you to upload and test your project

URL: l5k2a.instantcloud.cn

User: l5k2a
Password: v72sK32fCx0C4n6mcnzL

DB name: l5k2a
DB user: 8108f22f1d2c
DB pass: 57b6f15075262f11

**Comment by 492793425** [comment]
We have finished the system development, and I will upload the system code

**Comment by xinyanzu1** [comment]
sure--    发自新浪邮箱客户端
在 5月29日 10:42，Leo <notifications@github.com> 写道：

We have finished the system development, and I will upload the system code

&mdash;
